# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170325_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(default='moderate', max_length=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
