# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(1, 'Biolgy'), (2, 'Chemical'), (3, 'Chemistry'), (4, 'Computer Science'), (5, 'Economics'), (6, 'EEE'), (7, 'ENI'), (8, 'Maths'), (9, 'Mechanical'), (10, 'Physics'), (11, 'Fiction'), (12, 'Non-Fiction'), (13, 'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Moderate'), (3, 'Old')], default=1),
        ),
    ]
