# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170326_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_sell',
            field=models.IntegerField(choices=[(1, b'Buy'), (2, b'Sell')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(1, b'Biology'), (2, b'Chemical'), (3, b'Chemistry'), (4, b'Computer Science'), (5, b'Economics'), (6, b'EEE'), (7, b'ENI'), (8, b'Maths'), (9, b'Mechanical'), (10, b'Physics'), (11, b'Fiction'), (12, b'Non-Fiction'), (13, b'Others')], default=1),
        ),
    ]
