# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170326_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_sell',
            field=models.IntegerField(choices=[(1, b'Buy'), (2, b'Sell')], default=1),
        )
    ]
