# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170326_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(0, b'Arts & Photography'), (1, b'Biographies & Memoirs'), (2, b'Business & Money'), (3, b'Calendars'), (4, b"Children's Books"), (5, b'Comics & Graphic Novels'), (6, b'Computers & Technology'), (7, b'Cookbooks, Food & Wine'), (8, b'Crafts, Hobbies & Home'), (9, b'Christian Books & Bibles'), (10, b'Engineering & Transportation'), (11, b'Health, Fitness & Dieting'), (12, b'History'), (13, b'Humor & Entertainment'), (14, b'Law'), (15, b'Literature & Fiction'), (16, b'Medical Books'), (17, b'Mystery, Thriller & Suspense'), (18, b'Parenting & Relationships'), (19, b'Politics & Social Sciences'), (20, b'Reference'), (21, b'Religion & Spirituality'), (22, b'Romance'), (23, b'Science & Math'), (24, b'Science Fiction & Fantasy'), (25, b'Self-Help'), (26, b'Sports & Outdoors'), (27, b'Teen & Young Adult'), (28, b'Test Preparation'), (29, b'Travel')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
