# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20180611_1136'),
        ('books', '0018_auto_20180611_1206'),
    ]

    operations = [
    ]
