# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170326_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(default='Moderate', max_length=8),
        ),
    ]
