# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170326_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
