# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
