# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20170326_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.FileField(upload_to=''),
        ),
    ]
